[Variables]
Title=Applications
TotalGame=8
Directory=#@#App\

Gamecover1=firefox.png
Gamedir1=["C:\Program Files\Mozilla Firefox\firefox.exe"]
Gamename1=Firefox

Gamecover2=premiere.png
Gamedir2=["C:\Program Files\Adobe\Adobe Premiere Pro CC 2017\Adobe Premiere Pro.exe"]
Gamename2=Premiere
;Background2=Steam.jpg

Gamecover3=discord.png
Gamedir3=["C:\Users\Ethan\AppData\Local\Discord\Update.exe" "--processStart" "Discord.exe"]
Gamename3=Discord

Gamecover4=photoshop.png
Gamedir4=["D:\Program Files\Adobe Photoshop CC 2015\Photoshop.exe"]
Gamename4=Photoshop

Gamecover5=sketchbook.png
Gamedir5=["D:\Program Files\Autodesk SketchBook Pro 2021\SketchBookPro.exe"]
;Gamedir5=submenu:PowerMenu
Gamename5=Sketchbook

Gamecover6=setting.png
Gamedir6=submenu:SubdockSetting
Gamename6=Settings
Hotkey6=C

Gamecover7=outlook.png
Gamedir7=["shell:appsFolder\microsoft.windowscommunicationsapps_8wekyb3d8bbwe!microsoft.windowslive.mail"]
Gamename7=Mail
;Background7=GMS.jpg

Gamecover8=steam.png
Gamedir8=["C:\Program Files (x86)\Steam\steam.exe" "-tcp"]
Gamename8=Steam
