[Variables]
TotalGame=6
Directory=#@#App\

Gamecover1=firefox.png
Gamedir1=["C:\Program Files\Mozilla Firefox\firefox.exe"]
Gamename1=Firefox

Gamecover2=setting.png
Gamedir2=ms-settings:
Gamename2=Settings

Gamecover3=steam.png
Gamedir3=["C:\Program Files (x86)\Steam\steam.exe"]
Gamename3=Steam

Gamecover4=discord.png
Gamedir4=["C:\Users\Ethan\AppData\Local\Discord\Update.exe"]
Gamename4=Discord

Gamecover5=photoshop.png
Gamedir5=["C:\Program Files\Adobe\Adobe Photoshop CS6 (64 Bit)\Photoshop.exe"]
Gamename5=Photoshop

Gamecover6=premiere.png
Gamedir6=["C:\Program Files\Adobe\Adobe Premiere Pro CC 2017\Adobe Premiere Pro.exe"]
Gamename6=Premiere Pro

Gamecover7=premiere.png
Gamedir7=["C:\Program Files\Adobe\Adobe Premiere Pro CC 2017\Adobe Premiere Pro.exe"]

Gamecover8=controller.png
Gamedir8=!Execute [!WriteKeyValue "Variables" "filelayout" "page_game.inc" "#SKINSPATH#\GameHub 2\@Resources\Settings.inc"][!ActivateConfig "GameHub 2" "GameHUB.ini"]


Gamecover9=document.png
Gamedir9=E:\Google Drive\Notes.txt

Gamecover10=5a784ec0690086599e28f84b.png
Gamedir10=["C:\Users\Public\Desktop\VLC media player.lnk"]

Gamecover11=VLC media player.lnk
Gamedir11=["C:\Users\Public\Desktop\VLC media player.lnk"]

Gamecover12=setting.png
Gamedir12=ms-settings:
