[Variables]
Title=Bookmarks
TotalGame=8
Directory=#@#App\

Gamecover1=reddit.png
Gamedir1=https://www.reddit.com/
Gamename1=Reddit

Gamecover2=netflix.png
Gamedir2=https://www.netflix.com/
Gamename2=Netflix

Gamecover3=youtube.png
Gamedir3=https://www.youtube.com
Gamename3=Youtube

Gamecover4=deviantart.png
Gamedir4=https://www.deviantart.com/
Gamename4=Deviantart

Gamecover5=gmail
Gamedir5=https://mail.google.com/
Gamename5=Gmail

Gamecover6=github.png
Gamedir6=https://github.com/
Gamename6=Github

Gamecover7=unnamed.png
Gamename7=Translate
Gamedir7=https://translate.google.com/

Gamecover8=spotify.png
Gamename8=Spotify
Gamedir8=https://open.spotify.com/
