[Variables]
TotalGame=5
Directory=#@#App\

Gamecover1=reddit.png
Gamedir1=https://www.reddit.com/
Gamename1=Reddit

Gamecover2=gmail
Gamedir2=https://mail.google.com/
Gamename2=Gmail

Gamecover3=deviantart.png
Gamedir3=https://www.deviantart.com/
Gamename3=Deviantart

Gamecover4=youtube.png
Gamedir4=https://www.youtube.com
Gamename4=Youtube

Gamecover5=netflix.png
Gamedir5=https://www.netflix.com/
Gamename5=Netflix
