[Variables]
Title=Explorer
TotalGame=5
Directory=#@#App\

Gamecover1=gaming.png
Gamedir1=::{20D04FE0-3AEA-1069-A2D8-08002B30309D}
Gamename1=My Computer

Gamecover2=download.png
Gamedir2=folder:C:\Users\%USERNAME%\Downloads
Gamename2=Download

Gamecover3=user.png
Gamedir3=folder:C:\Users\%USERNAME%
Gamename3=%USERNAME%

Gamecover4=recent.png
Gamedir4=shell:recent
Gamename4=Recent

Gamecover5=rainmeter.png
Gamedir5=folder:"C:\Users\Ethan\OneDrive\Documents\Rainmeter\Skins"
Gamename5=Skin folder
