[Variables]
TotalGame=8
Directory=#@#App\

Gamecover1=gaming.png
Gamedir1=::{20D04FE0-3AEA-1069-A2D8-08002B30309D}
;Gamedir1=C:\Program Files\Mozilla Firefox\firefox.exe

Gamecover2=power.png
Gamedir2=submenu:PowerMenu

Gamecover3=app.png
Gamedir3=submenu:SubdockApp

Gamecover4=trashbin.png
Gamedir4=function:trashbin

Gamecover5=bookmark.png
Gamedir5=submenu:Subdock

Gamecover6=volume.png
Gamedir6=submenu:VolumeControl[VolumeBar.ini]

Gamecover7=movie.png
Gamedir7=!Execute [!WriteKeyValue "Variables" "filelayout" "page_movie.inc" "C:\Users\Ethan\OneDrive\Documents\Rainmeter\Skins\\GameHub 2\@Resources\Settings.inc"][!ActivateConfig "GameHub 2" "GameHUB.ini"]

Gamecover8=controller.png
Gamedir8=!Execute [!WriteKeyValue "Variables" "filelayout" "page_game.inc" "#SKINSPATH#\GameHub 2\@Resources\Settings.inc"][!ActivateConfig "GameHub 2" "GameHUB.ini"]


Gamecover9=document.png
Gamedir9=E:\Google Drive\Notes.txt

Gamecover10=5a784ec0690086599e28f84b.png
Gamedir10=["C:\Users\Public\Desktop\VLC media player.lnk"]

Gamecover11=VLC media player.lnk
Gamedir11=["C:\Users\Public\Desktop\VLC media player.lnk"]

Gamecover12=setting.png
Gamedir12=ms-settings:

Gamecover13=controller.png
Gamedir13=[!ActivateConfig "GameHUB 2" "GameHUB.ini"]
Gamedir#Edit#=["C:\Users\Ethan\Downloads\just-a-bin.zip"]
