[Variables]
Title=Settings
TotalGame=5
Directory=#@#App\

Gamecover1=wifi.png
Gamedir1=function:wifi
Gamename1=Wi-fi

Gamecover2=airplane.png
Gamedir2=function:airplane
Gamename2=Airplane

Gamecover3=bluetooth.png
Gamedir3=function:bluetooth
Gamename3=Bluetooth

Gamecover4=volume.png
Gamedir4=submenu:VolumeControl[VolumeW11.ini]
Gamename4=Volume

Gamecover5=setting.png
Gamedir5=ms-settings:
Gamename5=System
