[Variables]
style=classic

size=70
space=0
;icon size
background=0,0,0,150
;background_width=60

divider=4
;how slow animation calculation should be (increase to make animation longer)

animspd_init=150
animspd_enter=30
animspd_exit=20
;animation speed

update_rate=15

step=24
;how many update to draw when interacted (increase for longer animation)

expand=2
;how big icon expand when highlighted (size multiplier)

padding=15
;increase to make icon smaller

autohide=0
timeout=1500
cooldown=1000
; whether to hide icon

direction=1
;direction of the skin, 1:up  2:down  3:left  4:right


