[Variables]
TotalGame=9
Directory=#@#App\

Gamecover1=firefox.png
Gamedir1=C:\Program Files\Mozilla Firefox\firefox.exe

Gamecover2=gms2_logo_512.png
Gamedir2=steam://rungameid/585410

Gamecover3=gaming.png
Gamedir3=::{20D04FE0-3AEA-1069-A2D8-08002B30309D}

Gamecover4=document.png
Gamedir4=E:\Google Drive\Notes.txt

Gamecover5=VLC-Media-Player-icon.png
Gamedir5=C:\Program Files\VideoLAN\VLC\vlc.exe

Gamecover6=download.png
Gamedir6=C:\Users\Ethan\Downloads

Gamecover7=unikey.ico
Gamedir7=D:\Program Files\UniKeyNT.exe

Gamecover8=gmail.png
Gamedir8=C:\Program Files\Mozilla Firefox\firefox.exe" "https://mail.google.com/mail/u/2/

Gamecover9=5a784ec0690086599e28f84b.png
Gamedir9=C:\Program Files\Mozilla Firefox\firefox.exe" "https://mail.google.com/mail/u/2/

Gamecover10=5a784ec0690086599e28f84b.png
Gamedir10="C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" "https://mail.google.com/mail/u/2/"

Gamecover11=unknown.png
Gamedir11=C:\Program Files (x86)\Steam\Steam.exe

Gamecover12=5a784ec0690086599e28f84b.png
Gamedir12=ms-settings:

Gamecover13=controller.png
Gamedir13=[!ActivateConfig "GameHUB 2" "GameHUB.ini"]
