[Variables]

size=70
;icon size

background=245,245,245
;Background color, delete this line remove background

;background_width=60

update_rate=10
;Redraw delay (framerate delay)

padding=12
;increase to make icon smaller

focus=1
;Whether to hide icons when a submenu is open
snap=1
;Whether to snap sub-menu position to dock (when focus is false)

move_file=1
;Whether to move file instead of copy when drag and drop file in

direction=1
;direction of the skin, 1:up  2:down  3:left  4:right

FontColor=0,0,0
FontSize=15
TextY=10
TextW=0
TextBackground=255,255,255
;Color and size icon name
