[Variables]
style=classic

size=70
space=0
;icon size

divider=4
;how slow animation calculation should be (increase to make animation longer)

step=24
;how many update to draw when interacted (increase for longer animation)

animspd_init=80
;animation speed, how fast does icon pop up initially
animspd_enter=20
animspd_exit=40

update_rate=15

expand=2
;how big icon expand when highlighted (size multiplier)

padding=15
;increase to make icon smaller

autohide=1
timeout=1000
cooldown=1000
; whether to hide icon

vertical=0
;0 for horizonal dock, 1 for vertical

direction=1
; direction can be 1, 0 or -1

background=0,0,0,200
