[Variables]
style=grid

space=15
;space between icon, if other than 0 the icon will fix in their position

divider=4
;how slow animation calculation should be (increase to make animation longer)

animspd_init=50
animspd_enter=30
animspd_exit=20
;Speed for various animation

step=24
;how many update to draw when interacted (increase for longer animation)

expand=1.6
;how big icon expand when highlighted (size multiplier)


autohide=1
;Whether to hide icon after period of time

timeout=1000
;Timeout for autohide

cooldown=2000
; Cooldown after click on an icon

column=4
direction=1
;How many app column to display
