[Variables]
style=grid

space=10
;space between icon, if other than 0 the icon will fix in their position


background=10,10,15,256
;Background color, delete this line remove background

divider=4
;how slow animation calculation should be (increase to make animation longer)

animspd_init=100
animspd_enter=30
animspd_exit=20
;Speed for various animation

step=24
;how many update to draw when interacted (increase for longer animation)

expand=1.5
;how big icon expand when highlighted (size multiplier)

padding=8
;increase to make icon smaller

autohide=1
;Whether to hide icon after period of time

timeout=1000
;Timeout for autohide

cooldown=1000
; Cooldown after click on an icon

column=3
direction=1
;How many app column to display

FontColor=255,255,255
TextBackground=0,0,0,100
